#!/bin/bash


if [ $# != 3 ]; then
	echo "Usage: preproc <file_to_preprocess> <barcode_file> <adapter_file>"
	exit 1
fi

IN_FILE=$1
BC_FILE=$2
ADPTRS=$3
IN_BASE=`basename $IN_FILE .fastq`
tagdust -o $IN_BASE.cln.fastq -a $IN_BASE.aft.fastq -fdr 0.05 $ADPTRS $IN_FILE 

splitBC $IN_BASE.cln.fastq --bcfile $BC_FILE --prefix ./ --suffix .fastq --mismatches 1 --bol  

for base in `cut -f1 $BC_FILE`; do
	repair -s .fastq $base $base.fastq
done
#######################################################################	
#
# Usage: repair [options] <base> <reads.in>
#  where 
#        <base>       basename for output files
#        <reads.in>   a list of files containing all reads to re-pair
#                   Files can be in fastq or fasta format, but all
#                     files must be in the same format. If no read files 
#                     are listed, input is read from standard in.
#  options:
#         -p <string> a prefix to add to <base>. This can be used to
#                     specify an output directory.
#         -s <string> the suffix to append to the output files.
#         --shuf      print pairs in one file where paired reads are printed
#                     on consecutive lines (a.k.a. shuffled).
#         --split     split a set of shuffled reads up into two files.


