#!/usr/bin/perl -w


use strict;
use warnings;

sub usage;


if (@ARGV != 2) {
	usage();
	exit -1;	
}


my $map_file=$ARGV[0];
my %tag_map;


open (MAP,"<$map_file");

my @pair;

while (<MAP>) {
	chomp;
	@pair = split;
	$tag_map{$pair[0]} = $pair[1];
}

my $fasta_file=$ARGV[1];
open (FA,"<$fasta_file");
my $key;
my $read;
my $name;
while (<FA>) {
	chomp;
	$key = substr $_, 1;
	$read =	<FA>;
	chomp $read;
	if (exists($tag_map{$key})) {
		print STDOUT ">".$tag_map{$key}."\n".$read."\n";
	}
}


sub usage() {
	
	print "Usage: reptile_rename <file.map.txt> <corrected.fasta>\n"; 

}


