#!/bin/bash

if [ $# != 10 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
	prog=`basename $0`
	exit
fi
#exit
base=$1     # basename of paired files. Note: filenames names have the following format: <base>_p1.fastq <base>_p2.fastq 
Q=$2        # quality score cutoff for trimming reads
mnk=$3      # the minimum k-mer size for iterative de Bruijn graph assembly
mxk=$4      # the maximum k-mer size for iterative de Bruijn graph assembly
mncnt=$5    # minimum k-mer frequency allowed while contiging 
ins=$6      # library insert size
mxHits=$7   # maximum number of hits of a read to contigs allowed during mapping
minPrs=$8   # minumum number of pairs required to link two contigs
mnCtgLen=$9 # minimum contig length to be used for scaffolding 
S=${10}      # output directory for mapping and scaffolding output


if [ ! -d $S ]; then
	mkdir $S
fi
trimfq ${base}.fastq $mxk $Q >> ${base}_tr.out 2>> ${base}_tr.err  
fq2fa ${base}.fastq.htqs ${base}.fasta.htqs 
idba -r ${base}.fasta.htqs -o ${base}_htqs_idba --mink $mnk --maxk $mxk --minCount $mncnt >> ${base}_ctg.out 2>> ${base}_ctg.err 


O="$S/${base}"
if [ ! -d $O ]; then
	mkdir $O
fi
pairfa $base.fasta.htqs 
#rm ${base}.fast[a,q].htqs  
shufFasta ${base}_p1.fasta ${base}_p2.fasta ${base}_shuf.htqs.fasta
prep_contigAseq_v1_x1.pl -contig ${base}_htqs_idba-contig.fa -mate ${base}_shuf.htqs.fasta -a $O >> ${base}_map.out 2>> ${base}_map.err   
#rm ${base}_shuf.htqs.fasta

bwa index -a is $O/contigs_sopra.fasta >> ${base}_map.out 2>> ${base}_map.err 
bwa aln -f $O/${base}_shuf.sai $O/contigs_sopra.fasta $O/${base}_shuf.htqs.fasta_sopra.fasta >> ${base}_map.out 2>> ${base}_map.err
bwa samse -n $mxHits -f $O/contigs_sopra.fasta.sam $O/contigs_sopra.fasta $O/${base}_shuf.sai $O/${base}_shuf.htqs.fasta_sopra.fasta >> ${base}_map.out 2>> ${base}_map.err 

parse_sam_v1_x2.pl -sam $O/contigs_sopra.fasta.sam -a $O >> ${base}_scaf.out 2>> ${base}_scaf.err
read_parsed_sam_v1_x3.pl -parsed $O/contigs_sopra.fasta.sam_parsed -d $ins -a $O >> ${base}_scaf.out 2>> ${base}_scaf.err 
scaf_v1_x4.pl -o $O/orientdistinfo_c5 -a $O -w $minPrs -L $minCtgLen>> ${base}_scaf.out 2>> ${base}_scaf.err
############################################################################### 
#
# BWA Usage 
#
# Usage: bwa samse [-n max_occ] [-f out.sam] <prefix> <in.sai> <in.fq>
# 
# Usage:   bwa index [-a bwtsw|div|is] [-c] <in.fasta>
#
# Options: -a STR    BWT construction algorithm: bwtsw or is [is]
#          -p STR    prefix of the index [same as fasta name]
#          -c        build color-space index
#
# Warning: `-a bwtsw' does not work for short genomes, while `-a is' and
#          `-a div' do not work not for long genomes. Please choose `-a'
#          according to the length of the genome.
#
#
# Usage:   bwa aln [options] <prefix> <in.fq>
#
# Options: -n NUM    max #diff (int) or missing prob under 0.02 err rate (float) [0.04]
#          -o INT    maximum number or fraction of gap opens [1]
#          -e INT    maximum number of gap extensions, -1 for disabling long gaps [-1]
#          -i INT    do not put an indel within INT bp towards the ends [5]
#          -d INT    maximum occurrences for extending a long deletion [10]
#          -l INT    seed length [32]
#          -k INT    maximum differences in the seed [2]
#          -m INT    maximum entries in the queue [2000000]
#          -t INT    number of threads [1]
#          -M INT    mismatch penalty [3]
#          -O INT    gap open penalty [11]
#          -E INT    gap extension penalty [4]
#          -R INT    stop searching when there are >INT equally best hits [30]
#          -q INT    quality threshold for read trimming down to 35bp [0]
#          -c        input sequences are in the color space
#          -L        log-scaled gap penalty for long deletions
#          -N        non-iterative mode: search for all n-difference hits (slooow)
#          -f FILE   file to write output to instead of stdout
#
###############################################################################

