all: fastalen revcomp rmctgs rmfastanl

fastalen: fastalen.cpp
	g++ -o fastalen fastalen.cpp

revcomp: revcomp.cpp
	g++ -o revcomp revcomp.cpp

rmctgs: rmctgs.cpp
	g++ -o rmctgs rmctgs.cpp

rmfastanl: rmfastanl.cpp
	g++ -o rmfanl rmfastanl.cpp
